### ISSUE TITLE
Issue with source background color

### ISSUE THREAD

**Issue by devleaks** [nelsonpecora/quiet-light-atom#4]
Hello,
I'm having a little trouble with this line:
.string .source, .text .source {
  background-color: #EAEBE6;
}
which cause the text selection to not be highlighted properly:

![with](https://cloud.githubusercontent.com/assets/6030167/7255809/f2c9114a-e84b-11e4-90bc-fdf154c413de.png)

![without](https://cloud.githubusercontent.com/assets/6030167/7255814/f8359fd6-e84b-11e4-8e66-f0d884cf857f.png)

If I double click on a word, it does not get highlighted.
If I remove that line, everything is perfect.
I use Unity as the UI theme. Atom 0.192.0.
(I'm coming from TextMate where quiet light was my favorite theme. Ever.)

**Comment by nelsonpecora** [comment]
Hmm, weird. Make a PR that removes that line and I'll merge it. Thanks!

**Comment by devleaks** [comment]
Well, before I make a PR, I like the subtle source code background. I was wondering if it is not a question of order in the style file, or may be a finer selector could do. (I tried .string .source, .text .source  + .is-focused a different places with no luck.) I'm just new to atom, and I don't know their style names.

**Comment by nelsonpecora** [comment]
Ahh, possibly. I'm also relatively new to atom (and have found myself switching back to sublime text on occasion), so I'm not sure.

**Comment by nelsonpecora** [comment]
After a bit of fiddling around, I think I figured it out. Pushed `v1.4.0`, which should work perfectly now.
